### ISSUE TITLE
Do not see anti ad blocker message but video doesn't play either

### ISSUE THREAD

**Issue by etoyoc** [TheRealJoelmatic/RemoveAdblockThing#148]
Just get black screen now

**Comment by czachor** [comment]
Same here, Firefox latest, latest plugin too.
Message in the console:

> Uncaught (in promise) ReferenceError: can't access lexical declaration 'observer' before initialization
>     window["__f__low9mr62.wmt"]/</< moz-extension://cd5baa07-2f20-492f-a8ae-545b07cab411/userscripts/Remove-Adblock-Thing.user.js?id=905b4834-de15-4244-aa79-3fee8ac36fbd:78
>     window["__f__low9mr62.wmt"]/< moz-extension://cd5baa07-2f20-492f-a8ae-545b07cab411/userscripts/Remove-Adblock-Thing.user.js?id=905b4834-de15-4244-aa79-3fee8ac36fbd:217
>     St https://www.youtube.com/watch?v=YQhY_qQdlxA:9
>     window["__f__low9mr62.wmt"]/< moz-extension://cd5baa07-2f20-492f-a8ae-545b07cab411/userscripts/Remove-Adblock-Thing.user.js?id=905b4834-de15-4244-aa79-3fee8ac36fbd:1
>     "__f__low9mr62.wmt" moz-extension://cd5baa07-2f20-492f-a8ae-545b07cab411/userscripts/Remove-Adblock-Thing.user.js?id=905b4834-de15-4244-aa79-3fee8ac36fbd:1
>     St https://www.youtube.com/watch?v=YQhY_qQdlxA:9
>     s https://www.youtube.com/watch?v=YQhY_qQdlxA:72
>     <anonymous> https://www.youtube.com/watch?v=YQhY_qQdlxA:75
>     g https://www.youtube.com/watch?v=YQhY_qQdlxA:69
> eval:78:21

**Comment by ldurniat** [comment]
Hi, 
![obraz_2023-11-13_101147160](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/22639656/db4bc745-0904-4668-9113-277c1473247f)

Opera 104.0.4944.54 Win 10
Tampermonkey and ad blocker scipt installed today.

**Comment by czachor** [comment]
Probably fixed in https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/145 v2.5 (still waiting for merge).

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
