### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by rahulbhargavaa** [TheRealJoelmatic/RemoveAdblockThing#150]
no ad and no Youtube videos playing, black screen showing

**Comment by nugentmichael1** [comment]
On page load the video swiftly flashes an "Ad blockers violate YouTube's Terms of Service" warning screen and then goes completely black.  Everything else is normal.
Firefox 119.0.1
Windows 10 Home (10.0.19045 Build 19045)

**Comment by McJones9631** [comment]
Also having this issue, Firefox 119.0.1 on Windows 10 Pro 22H2.

**Comment by mertgoksel** [comment]
Having this exact issue on Thorium (version 117.0.5938.157). Win11

**Comment by SiriMoel** [comment]
same here on chrome

**Comment by nugentmichael1** [comment]
> On page load the video swiftly flashes an "Ad blockers violate YouTube's Terms of Service" warning screen and then goes completely black. Everything else is normal. Firefox 119.0.1 Windows 10 Home (10.0.19045 Build 19045)

I did not follow instructions and did not white list YouTube.  Now that I have, everything works as intended.

**Comment by mertgoksel** [comment]
Guys, its not about thorium. Its about youtube enhancer extention. It somehow provokes the adblock blocker.

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
