### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Mugetsusaigo** [TheRealJoelmatic/RemoveAdblockThing#153]
using Arc Browser for Mac, I refresh the video multiple times and it's just a blank black screen, everything is installed and enabled

**Comment by nugentmichael1** [comment]
Did you white list YouTube from other ad block programs?  YouTube will detect them and block the video otherwise.

**Comment by nishanth1517** [comment]
how do you white list

**Comment by NsdHSO** [comment]
What block programs do you use?

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
