### ISSUE TITLE
Video not loading properly

### ISSUE THREAD

**Issue by MickeyFan1909** [TheRealJoelmatic/RemoveAdblockThing#158]
![Capture3](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/151090733/b4b66cca-48bb-4824-b382-9c867b5c9819)

I tried to load up a YouTube video on chrome. But it would not load up properly and it stays on a black screen. It works on Microsoft edge, but it takes 5/6 seconds to load.

Can you look into this issue on Chrome please?

**Comment by Lilyp3892** [comment]
same here

**Comment by ChodLord** [comment]
Yep same, getting a black screen with just the YouTube logo at the top, then after 6-8 seconds, video loads itself. Sometimes video doesn't load and only get a black screen where refreshing the page a couple of times gives me the 6-8 second pause before video starts.

**Comment by ljg37133** [comment]
Yep, happening to me on Firefox as well

**Comment by jimmyleocn** [comment]
same here

**Comment by dramr** [comment]
the ads are starting to pop back up again for a split sec before giving a black screen :))

**Comment by gogonuho** [comment]
same here Please solve it quickly

**Comment by ralinchan** [comment]
This isn't related to the ad script. This is on Google intentionally doing it (Youtube's polymer script) that times you out for 5000ms (5 seconds).

Link to the YT script: https://www.youtube.com/s/desktop/96766c85/jsbin/desktop_polymer_enable_wil_icons.vflset/desktop_polymer_enable_wil_icons.js

**Comment by hasimyerlikaya** [comment]
I'm using Opera, and I had the same issue.

I added YouTube to the exception list of Opera's built-in ad blocker extension, and I cleared YouTube cookies. 
After these, everything worked perfectly.

**Comment by ralinchan** [comment]
Fix: Append the following to your uBlockOrigin (dashboard -> my filters)

`www.youtube.com##+js(nano-stb, resolve(1), *, 0.001)`

**Comment by D3ltorohd** [comment]
I have the same problem with opera gx. The message was gone, but black screen where normaly the video is, and nothing happend. uBlock is off, i at the line above onder my filters to.

**Comment by CaptainPorc** [comment]
Ok so after trying all the fixes I found in the issues opened here and there, I've tried this specific situation that seems to work
- Ublock origin not On while on youtube
- OperaGX adblocker Off on youtube
- Cookies removed from youtube specifically 
- The last which solved it is that I had an extension which helped me get perfect settings for every video "Enhance Youtube" and when I toggled it off, it worked again 
- And also the script running obviously which gave me no-ads video with no prompt either
I'll keep you updated might be a placebo cause I tried some of thoses fix and they work for 1 day then all of a sudden went back to "black screen" so I hope this time will be the one

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
