### ISSUE TITLE
Shows blank screen when trying to see any video on youtube

### ISSUE THREAD

**Issue by RohitChapke** [TheRealJoelmatic/RemoveAdblockThing#169]
This has been happening since this morning, whenever I try to play any video on youtube, it first shows up the ad blocker popup for a millisecond and then turns the window into a blank screen where the video is supposed to play. Help me fix this issue. It was working perfectly fine till yesterday.

![Capture](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/50639785/229c568e-b58b-45bf-ab3f-b5dcca018237)

**Comment by orabeidm** [comment]
same problem

**Comment by Balan-dev** [comment]
i have the same problem just empty your cache on your web browser for the time being 

hope it's fix soon

**Comment by nstein5** [comment]
Open in a private window and ensure your extensions are enabled on private windows.

**Comment by kmt935** [comment]
Will follow this thread.  I am on a mission to get around this....

**Comment by Skarsgardsson** [comment]
> This has been happening since this morning, whenever I try to play any video on youtube, it first shows up the ad blocker popup for a millisecond and then turns the window into a blank screen where the video is supposed to play. Help me fix this issue. It was working perfectly fine till yesterday.
> 
> ![Capture](https://private-user-images.githubusercontent.com/50639785/288035579-229c568e-b58b-45bf-ab3f-b5dcca018237.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzI0NzUsIm5iZiI6MTcwMTgzMjE3NSwicGF0aCI6Ii81MDYzOTc4NS8yODgwMzU1NzktMjI5YzU2OGUtYjU4Yi00NWJmLWFiM2YtYjVkY2NhMDE4MjM3LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAzMDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZWY5OTdmNDVhYTUyM2QxMzU2NzQwMmQzNTFkMTVkN2Y3ZDFhZjhiYzdiNDc4MTliMDQ4YWZmZWY4Y2RhZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8NFoZTPOmqcDe8CRiRNj06vzKRyHfDo6YUPON1bAzs)

If you are having adblock issues on 12/6/23 - just clear your browser browsing data and cookies. This will make it work again.

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
