### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by waterscaped** [TheRealJoelmatic/RemoveAdblockThing#17]
As of 3:30PM EST on 10/15/2023, this no longer works. I am getting the Adblock Blocker pop-up again. Just putting this here so other people know.

**Comment by mjb2010** [comment]
I get the pop-up, and then it disappears right away. However, a dim overlay persists, blocking scrolling and the player's controls (volume, seek, etc.).

**Comment by niodium** [comment]
This happens because google added another div with dimmer and z-index. 
Add a line to the popupRemover function next to the popup constant declaration: 

`const backdrop = document.querySelector("tp-yt-iron-overlay-backdrop");`

and just below that, add a branch to the condition(example of a full condition):

```
if (popup) {
                if (debug) console.log("Remove Adblock Thing: Popup detected, removing...");
                popup.remove();
                if (backdrop) {
                    backdrop.remove();
                };
                unpausedAfterSkip = 2;
                if (debug) console.log("Remove Adblock Thing: Popup removed");
            }
```

**Comment by Demopans** [comment]
Probably a good idea to keep this issue open while updating it with whatever else Youtube comes up with

**Comment by Albedo-13** [comment]
Just created new PR that seems to fix this issue (hope so). Try out new script version after approval
