### ISSUE TITLE
Adblock message coming through and video not playing.

### ISSUE THREAD

**Issue by GoldenLogic** [TheRealJoelmatic/RemoveAdblockThing#174]
Hi looks like youtube made a new update today and the adblock message is coming through and videos are not playing as of december6 3:24 pm Arizona time.

**Comment by janvollgod** [comment]
same here 23:33 CET. They changed something. Window go full screen shortly then gets back, but video stay black, nothing goes

**Comment by GoldenLogic** [comment]
Hopefully they can fix the issue soon. We should prob expect youtube changes to happen more frequently now.

**Comment by GoldenLogic** [comment]
Actually if your using a different browser than chrome then you should prob disable to built-in adblock, that fixed my issue, for now.

**Comment by Tharki-God** [comment]
this happens due to another adblocker filter which is `youtube.com###player-ads`

:)

**Comment by TheRealJoelmatic** [comment]
Try the latest version or

## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
