### ISSUE TITLE
Doesn't start the video 

### ISSUE THREAD

**Issue by DEFINETLYNOTANERD** [TheRealJoelmatic/RemoveAdblockThing#181]
When im click a video its show youtube adblock warning for a sec then its just blank.Video doesn't play
Hope you fix it in a short time

**Comment by OzzyMouse** [comment]
Been happening to me also it  blocks ads on youtube but it also stops the video from showing unfortunately  and just gives you a black screen on the player and you have to fresh/reload for it to work and 70% of the time it doesn't

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
