### ISSUE TITLE
sometimes it blocked me

### ISSUE THREAD

**Issue by chybbud** [TheRealJoelmatic/RemoveAdblockThing#208]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/125054868/57bb5437-eccd-43ea-b2b1-bf8b896290d1)

please note that the extension i only active is Tampermonkey

**Comment by Altex2** [comment]
> ![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/125054868/57bb5437-eccd-43ea-b2b1-bf8b896290d1)
> 
> 
> 
> please note that the extension i only active is Tampermonkey

Keep in mind that this script is still a work in progress very much and it will become better in time , for now is better then nothing, i will try to remake some parts of the code when i have time because i found aome issues

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
