### ISSUE TITLE
Youtube still blocking on Chrome 120.0.6099.110 and latest build 2.8

### ISSUE THREAD

**Issue by Robpcfl** [TheRealJoelmatic/RemoveAdblockThing#224]
**Describe the bug**
Youtube still blocking on Chrome 120.0.6099.110 and latest build 2.8.  Just updated to latest version of Chrome and after a few moments of playing any video on YouTube it detects an ad blocker.  I have disabled both the ad blocker and "Remove Adblock Thing", and still comes up.  I have put Chrome in Developer Mode per Tampermonkey, and issue still present.  Only thing that has changed on the system is updating to latest build of Chrome.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 120.0.6099.110

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
