### ISSUE TITLE
cant close youtube tv popup 

### ISSUE THREAD

**Issue by Carlcamp** [TheRealJoelmatic/RemoveAdblockThing#228]
**Describe the bug**
when watching any video a popup of "try youtube premium/ try youtube tv" pops up and cant close it.

**To Reproduce**
1. watch video
2. wait a while
3. ad try's to play
4. popup appears

**Expected behavior**
popup doesn't show/ can close it

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/3106411/50d4351b-101d-47e9-a0cf-09a9b3b10673)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 120.0.6099.110 (Official Build) (64-bit)

**Comment by mickleby** [comment]
I figure this is the same as what I'm having.
<img width="958" alt="image" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/1623707/bcc123ad-983b-4243-9643-4496c3b7de97">
The last "modal" popup window gets painted at weird places. Maybe the element wasn't properly dismissed so that it could be deleted? 🤷

Refreshing the page clears the DOM, but some new popup will get "stranded in limbo" soon enough! 😆
