### ISSUE TITLE
It stop working from yesterday - after 2-3 refreshes of youtube it manage to do it but it is a problem :(

### ISSUE THREAD

**Issue by venzislav** [TheRealJoelmatic/RemoveAdblockThing#229]
From yesterday it stop blocking the message from youtube and cannot play video. After few refreshesh it removes the youtube warning but the next video is the same situation - need of few refreshesh before play something. I get this :

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/22798485/95182e05-728d-49a8-862e-b4ff689d5f48)

**Comment by gogonuho** [comment]
me to

**Comment by calchip** [comment]
Same thing here. Firefox on Mac. Worked perfectly until a day or two ago.

**Comment by corwin0501** [comment]
same, it fail

**Comment by venzislav** [comment]
I forget to say that I am on firefox under linux if that helps ?

**Comment by DabMK** [comment]
Same thing on Opera GX

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
