### ISSUE TITLE
no longer working in chrome

### ISSUE THREAD

**Issue by Abkbhuiyan** [TheRealJoelmatic/RemoveAdblockThing#230]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MasterTraits** [comment]
**Describe the bug**
Adblocker not functioning as of late december 23, UTC 8:00

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Youtube 
2. Click a Video

**Expected behavior**
Appropriately, It should not show any instances of Youtube noticing you have an adblocker.

**Screenshots**
https://imgur.com/a/irz9d8k

**Desktop:**

OS: Linux
Browser Vivaldi: Google Chrome Client
Version: 6.4.3160.47 (Stable channel)

**Comment by TheRealJoelmatic** [comment]
> **Describe the bug** Adblocker not functioning as of late december 23, UTC 8:00
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Youtube
> 2. Click a Video
> 
> **Expected behavior** Appropriately, It should not show any instances of Youtube noticing you have an adblocker.
> 
> **Screenshots** https://imgur.com/a/irz9d8k
> 
> **Desktop:**
> 
> OS: Linux Browser Vivaldi: Google Chrome Client Version: 6.4.3160.47 (Stable channel)

## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
