### ISSUE TITLE
Script blocked by Youtube

### ISSUE THREAD

**Issue by SplatSoda** [TheRealJoelmatic/RemoveAdblockThing#234]
So apparently, Youtube blocked my video player. My AdBlock was allowing ads to go through, but YouTube has likely caught on to this script. Any ways on how to fix it?

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/84022739/0241a019-f0eb-4cb8-926f-f4bc32f18292)

**Comment by atiilla** [comment]
you need to disable the adblock extension for YouTube.com and exclusively use the Tampermonkey script

**Comment by skadygks** [comment]
I'm experiencing the same issue at msedge

**Comment by ShiniDev** [comment]
Seconded, ublock extension is disabled on youtube, but youtube adblock pops up. This does not happen previously.

**Comment by ngovandang** [comment]
clear cookies and data/history of youtube and google on your browser, relogin and everything should be fine
If it's giving headaches for you then just clear entire of cookies + history of your browser

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
