### ISSUE TITLE
Adblock detected

### ISSUE THREAD

**Issue by TashaSquirrel** [TheRealJoelmatic/RemoveAdblockThing#239]
**Describe the bug**
Youtube adblock would start triggering at random times even with the AdBlock disabled.

**To Reproduce**
1. Go to Youtube
2. Click on a video.
3. Keep clicking on a video until a message pops up. (this can also be quickly triggered by playing another video via home page while the video is minimized

**Expected behavior**
As mentioned in the description, the adblock is triggered (quickly triggered if attempting to play a video at the home screen while the video is minimized),

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/155065811/b6b46733-137f-48f5-b111-5de7d1755634)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/155065811/95ecccda-5ebc-4a50-a035-1d15cc8000b9)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 120.0.6099.129/130

**Additional context**
Refreshing the page would solve the issue temporarily.

**Comment by niriho** [comment]
I'm having the same issue. Hope you can resolve it.

**Comment by minhchienwikipedia** [comment]
Same issue

**Comment by pr3dicament** [comment]
Same issue--arch linux with cinnamon.  Hope this can work again.

**Comment by shivam8800** [comment]
I am still facing this issue but after reloading everything works fine
I don't want to clear any cookies or something, any suggestions ?

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
