### ISSUE TITLE
Blank display on newest removeadblockthing

### ISSUE THREAD

**Issue by qordnjs** [TheRealJoelmatic/RemoveAdblockThing#256]
Blank display when playing youtube.
I must to hotkey: Windows Tab, then go back chrome and see it.
Please fix it.

OS: WIndows 23h2 build 22631.3007
Browser: Chrome 120.0.6099.217

**Comment by qordnjs** [comment]
After resetting the notebook precision 5570, The popup appears everytimes clicking the next play:
"Ad blockers violate YouTube's Terms of Service
It looks like you may be using an ad blocker. Video playback is blocked unless YouTube is allowlisted or the ad blocker is disabled.
Ads allow YouTube to be used by billions worldwide.
You can go ad-free with YouTube Premium, and creators can still get paid from your subscription."

**Comment by TheRealJoelmatic** [comment]
Is this an issue with the new update you installed?

## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.

**Comment by qordnjs** [comment]
Today Jan 12th I update the newest verion 3.1 Everything is ok. No blank display, no F5 (refresh) everytime the next play on youtube.
Thank you very much.
