### ISSUE TITLE
 "Ad blockers violate YouTube's Terms of Service" message since updating the script

### ISSUE THREAD

**Issue by TheRealPepsi** [TheRealJoelmatic/RemoveAdblockThing#258]
**Describe the bug**
I'm getting the "Ad blockers violate YouTube's Terms of Service" message since updating the script

**To Reproduce**
Clicking on any video

**Expected behavior**
The video should load without showing the ad blocker message

**Screenshots**
I think we've all seen it before lol

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: v1.61.116

**Additional context**
It was working perfectly fine until the latest update, is this just me who's getting this? I've tried uninstalling and reinstalling the script, but nothing. Thanks for reading!

**Comment by AndreasFromDanmark** [comment]
@TheRealPepsi Same here

OS: Windows
Browser: Google Chrome
Version: v120.0.6099.217

**Comment by jcliffy** [comment]
I was on Youtube about 30 minutes ago when they nuked it right before the youtube block thing update and it started saying disabling videos, then the  fast patch update came out; downloaded it and it is still saying the same thing. So i think he's working on it now trying to figure it out, but no latest update not working for me.

**Comment by StatisticallyinSignificant** [comment]
Same issue
Google Chrome Version 120.0.6099.217

Additionally, it doesn't work well anymore with playlists. It just refreshes to the next video and then the next video constantly.

**Comment by StatisticallyinSignificant** [comment]
Same issue
Google Chrome Version 120.0.6099.217

Additionally, it doesn't work well anymore with playlists. It just refreshes to the next video and then the next video constantly.

**Comment by TahaKeremEris** [comment]
Same for me. v2.9 blocks ads but videos load very slowly. In v3.1 ads showing.

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
