### ISSUE TITLE
Anti Adblock will not go away now

### ISSUE THREAD

**Issue by MonX23** [TheRealJoelmatic/RemoveAdblockThing#266]
Yeah so for some reason it's not working and it makes it look like it needs an update, when it clearly doesn't
-
Browser: Microsoft Edge
Version: 5.0
I have UBlock Origin also
![df1a138d83a8c4faf6135f1e6de2befd](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/148668212/49bcb49c-f613-4e07-84d3-1c8b297803c3)

**Comment by adityak368** [comment]
+1

**Comment by MonX23** [comment]
what do you mean +1?

**Comment by adityak368** [comment]
doesnt work anymore

**Comment by Toku69** [comment]
yes it does just revert to an older version

**Comment by Andatti** [comment]
My script went from 2.9 to 3.0 and 3.1 today and it stoped working but the github is still at 2.9, I downgraded it and it works fine now
So I suggest to use the script version 2.9

**Comment by eos1d3** [comment]
3.1 works well for me.

**Comment by KyuuGryphon** [comment]
Neither 2.9 nor 3.1 are working here anymore. Trying 3.0 momentarily.

**Comment by KyuuGryphon** [comment]
Nope, 3.0 isn't working here either. I either get an ad, or the "ad blockers are not allowed" pop-up. Was working fine until I was prompted to update to 3.1 earlier today.

**Comment by Andatti** [comment]
Make sure you don't have any adblock extension enabled

**Comment by KyuuGryphon** [comment]
I don't. I double-checked - neither GX's built-in adblock or uBlock Origin are running on YouTube.

**Comment by DarthSonic** [comment]
Same for me. 3.1, Edge, AdBlock popup is showing all the time. No AdBlocker installed.

**Comment by TheRealJoelmatic** [comment]
Make sure to update to 3.2.

## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.

**Comment by LIBO-WT** [comment]
> +1是什么意思？

Said to have the same problem

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
