### ISSUE TITLE
Message still shows

### ISSUE THREAD

**Issue by DyRYX** [TheRealJoelmatic/RemoveAdblockThing#312]
**Script version**
3.2

**Describe the bug**
Message still shows, on every video I click

**Expected behavior**
It started all from today 14th January, opened YouTube, played a video and boom the message shows up again. Tried to reinstall or update, but nothing worked.

**Screenshots**
![grafik](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/66790878/90d84b0a-0956-4c8b-ba82-a0cc1b7b121a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 121.0.1

**Additional context**
Deactivating AdBlocker doesn't help tho, ads still play even if the script is activated!

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
