### ISSUE TITLE
Still asks for update

### ISSUE THREAD

**Issue by SimonPetra03** [TheRealJoelmatic/RemoveAdblockThing#354]
Version 3.7

Bug:
Opera keeps offering me to download 3.5 version of the script, I download it, change the script with the asked version, but nothing changes.

Expected Behavior:
To update itself and stop asking for new update.

Desktop
Win 10, 22H2, using Opera

If anyone could help me with this, maybe I am doing something wrong with the script, please tell me.

**Comment by Naginreed** [comment]
Hi, it should look something like this whenever you open Opera and open a new Youtube video
___
**1. Get a Pop-Up on Top which says this**
![1](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/5d24c8f5-faca-472e-940b-f9db96cc5100)
**-> Click on OK**
___
**2.  a new Tab should open with a Tampermonkey site asking you to either Update or Cancel**
![2](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/7ce2ca58-7ba3-4826-9523-b90bb56a8943)
**-> Click Update**

_It also happened to me once that it Downloaded the file instead of opening the new Tab, but i wasnt able to replicate it. If it still downloads it try using this [Link](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/main/Youtube-Ad-blocker-Reminder-Remover.user.js?raw=True)_
___
**3. Restart the Browser**
