### ISSUE TITLE
Half of player icons is gone

### ISSUE THREAD

**Issue by oomek** [TheRealJoelmatic/RemoveAdblockThing#3598]
**Script version**
5.6

**Describe the bug**
Half of player icons is gone with script enabled.
I'm especially missing the icon for Zoom To Fill extension which I'm using daily.

**Screenshots**

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/2974860/e9eb786f-a1e4-4845-8095-0f26793f1e84)

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/2974860/0d9d2d78-ba28-47ee-bb08-cc700dbf90ba)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Vivaldi
 - Version 6.7.3329.41

**Comment by blakexe** [comment]
Prevents autoplay in playlists too, extremely annoying

**Comment by luminilux** [comment]
Unfortunately the way the script currently works is not allowing for several things:

- Playlist autoplay doesn't work
- Miniplayer doesn't work
- Member videos don't work
- Watch history doesn't work / Videos are not marked as seen

The video is displayed in a separate frame which does not detect that you are logged in and technically is not part of the Youtube website but its own document.

Because Youtube is detecting the other ways there is not much we can do about that at the moment.

**Comment by oomek** [comment]
I understand. This is an acceptable compromise. Apart from this minor annoyance the current version works great for me. Thank you for not giving up.
