### ISSUE TITLE
"Remove Adblock Thing: A new version is available. Please update your script. " Notification won't go away

### ISSUE THREAD

**Issue by vexillologist1337** [TheRealJoelmatic/RemoveAdblockThing#361]
Remove Adblock Thing: A new version is available. Please update your script. Notification for nearly EVERY website I visit and every new tab I open. It's quite annoying and I cannot do anything until I click a button. I've tried clicking Ok and Cancel and neither gives me a valid option. Even when I uninstall the script and even when I uninstall TamperMonkey the problem still occurs. I just want it gone.

I've tried what people have done to fix the issue, those don't work for me. Like changing const Update to false and whatnot.

Running Chrome on MacBook Pro.

**Comment by AgentRev** [comment]
It'd be great if popups could be permanently disabled, since Tampermonkey already checks for updates once a day

**Comment by MorkaZ** [comment]
please delete it.. Feels like my browser is virused

**Comment by Naginreed** [comment]
> Even when I uninstall the script and even when I uninstall TamperMonkey the problem still occurs

Since this is Java-Script run locally from your Browser Extension TamperMonkey, this makes no sense.
Be aware that after every Change/Update or even Deletion you make, you need to
**Restart your Browser (not just the tab)**

> I've tried clicking Ok and Cancel and neither gives me a valid option.

What do you mean with no valid option? 
If you click OK a new Tab should open with Tampermonkey Update Interface like below
![2](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/692b69aa-0188-44eb-bdc9-f00877fceb44)
Then you hit Update and it should be Up-To-Date after a
**Restart your Browser (not just the tab)**

Worst thing that can happen that the Updated File gets Downloaded *(Name: Youtube-Ad-blocker-Reminder-Remover.user.js)* which you can install manually

**Comment by TheRealJoelmatic** [comment]
In the newer versions we have a less intrusive update check
