### ISSUE TITLE
New Update - Ads still play

### ISSUE THREAD

**Issue by vetteengr** [TheRealJoelmatic/RemoveAdblockThing#362]
**Script version**
3.8

**Describe the bug**
Have 3.8 installed. Ads still play after couple songs in the playlist or if I click on a new song. On chrome. Windows 11.

Thank you for a great tool, would love for it to really skip the ads everytime. Thank you again....

**Comment by oomek** [comment]
Same here version 3.8 is still showing the nag screen
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/2974860/f58fe6d1-779f-4675-938e-1ef313ae2456)

**Comment by Ikanni123** [comment]
An add pops up but it doesn't play, however it stops at the end of the add where the skip button appears. You can then press on the skip button and resume the video but it keeps happening several times. Why can't this be fixed?

**Comment by vetteengr** [comment]
> Same here version 3.8 is still showing the nag screen ![image](https://private-user-images.githubusercontent.com/2974860/298307318-f58fe6d1-779f-4675-938e-1ef313ae2456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODY0MDEsIm5iZiI6MTcwNTc4NjEwMSwicGF0aCI6Ii8yOTc0ODYwLzI5ODMwNzMxOC1mNThmZTZkMS03NzlmLTQ2NzUtOTM4ZS0xZWYzMTNhZTI0NTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMjEyODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBlMjg2MTA3ZDI2YTA1OTk2ZWIwNDI3NzdmYWQ1NjVjNWViYmY1MjExZjJhMmNiOTI1NjY2MTM2MTJkYTE2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3Jkg7dL5QlWzCbf7UvFsikSAwemtl0iOGj8agJfAW9g)

You will still need to disable Ad Block - however, the script is supposed to skip ads. Try and disable your Ad Blocker.

**Comment by oomek** [comment]
I have Vivaldi's adblocker disabled on youtube. No other adblocking extensions enabled.
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/2974860/28f8d5a0-dd2e-4a1d-8688-7ce89d00a0ad)

**Comment by Naginreed** [comment]
# @vetteengr - Ad blockers doesn't work at all

If you are still seeing the full Ads at the beginning of a video or randomly in the middle of some videos
the script is most likely not active.


___
**Steps to check**
- [ ] Show Tampermonkey on your Extension 
- [ ] Go to https://www.youtube.com
- [ ] Check the Tampermonkey Symbol on the Top Right if it shows a loaded Script _(small 1 in red on the symbol)_
![ytadbl_chrome_tamp-on-bar3](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/6543ced4-1068-4c7f-b073-e466abe9e532)
If not the script is not loaded
___
**How-To's** _(click on them to Expand)_
<details><summary> <b>How-To <code>Show Tampermonkey on your Extension</code></b></summary>

- Click on the Extensions Symbol on the Top right (1)
- Pin the Tampermonkey Extension to make it visible on the Extension Bar (2)
![ytadbl_chrome_tamp-on-bar](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/a1b6eae2-2e82-4820-8abe-2f00d8cd79f7)
</details>
<details><summary> <b>How-To <code>Enable Tampermonkey & Script</code></b></summary>

- Check if Tampermonkey itself is enabled (1) 
- and the Script is enabled (2)
![ytadbl_chrome_tamp-on-bar2](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/a6441278-216d-43ae-a7b1-81e71bcb2b23)
-  !!!! After this restart the Browser and Check again !!!!

</details>

___
# @oomek - Ad blocker Pop-Up
**Things to check**
- Have you restarted the Browser after you disabled your Adblocker?
- Are you sure you turned every Adblocker off? Like checked all your Chrome Extensions?
- Do you use any Proxies that might have blocking abilities?
- Do you maybe use a DNS server that blocks certain domains like a pi-hole or similar?

This pop-up only shows up when Youtube detects Ads being blocked, 
which the script should not trigger otherwise it should be more widespread.

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
