### ISSUE TITLE
Suddenly script stopped working

### ISSUE THREAD

**Issue by DinerzReady** [TheRealJoelmatic/RemoveAdblockThing#364]
**Script version**
 3.8
**Describe the bug**
Suddenly stopped working and youtube is again showing the "Adblock thing"

**Expected behavior**
Should be working properly , it just worked a few hours ago :( 

**Screenshots**
![(128) ANIMAL_ Marham (Pehle Bhi Main) (Song) Ranbir Kapoor,Tripti Dimri _Sandeep_Vishal M,Raj S_Bhushan K - YouTube — Mozilla Firefox 1_21_2024 7_25_33 PM](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/46134179/657ca046-f625-415e-978d-c2fd2b2bb966)

**Desktop **
 - OS: Windows 10 pro 64 bit
 - Browser : Firefox
 - Version : 121.0.1 64 bit

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.

**Comment by DinerzReady** [comment]
> ## Common Issues
> 
> **"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**
> 
> This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:
> 
>     * **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.
> 
>     * **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.
> 
>     * **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.
> 
>     * **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.
> 
>     * **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.

Thanks for that , checked the issue and what I came up with is :
1 . Adblock extension (Specifically Adblock one out there) is causing the problem
2 . The problem is happening with other adblockers except ublock . So I shifted to ublock with custom filters .
Now everything is fine , but IDK why this issue happened because before this I used the script along with 3 adblockers and it did just fine . Maybe next update will fix it :D . Thanks Author , you are a life-saver ! <3
