### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by soshin1337** [TheRealJoelmatic/RemoveAdblockThing#366]
**Script version**
3/8

**Describe the bug**
Not working

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 64 bit 22h2
 - Browser chrome
 - Version 120.0.6099.225

**Screenshots**

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/15040527/451b3e12-ea0c-479c-8a6a-e1805268490c)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/15040527/a04b4aea-4bff-40a4-af09-1e138d99e596)

AdBlock disabled, other tampermonkey scripts disabled

**Comment by Naginreed** [comment]
- Have you restarted the Browser after you disabled your Adblocker?
- Are you sure you turned every Adblocker off? Like checked all your Chrome Extensions?
- Do you use any Proxies that might have blocking abilities?
- Do you maybe use a DNS server that blocks certain domains like a pi-hole or similar?

**Comment by soshin1337** [comment]
1) yes
2) yes
3) no
4) Dns 1.1.1.1

**Comment by Naginreed** [comment]
Hmm.. then im running out of ideas honestly, i have the same Win and Chrome Version tested, but for me it works just fine.

This pop-up only shows up when Youtube detects Ads being blocked, (often DNS or Connection-Blocks)
which the script should not trigger, since its just running locally and afaik just manipulates the html.
Also it wouldn't work for nobody if youtube was able to detect it.

My only guess would be that either an other extension in chrome, firewall-setting, any "privacy protection stuff"
interrupts the youtube ads and gets detected. Hence the Pop-Up
Have you tried "for testing purpose" to use a browser with no extensions besides the script enabled or turning off firewall?

**Comment by slzero-X** [comment]
If you have everything checked in the readme, you have to have something else that is triggering its anti-adblock somehow, I am aware that there are many differing factors that can trigger it, and I have my only adblocker disabled on YouTube and the bypassing script is the only tampermonkey script I have, since its really the only thing I really need, and its working perfectly well.

Therefore its straight up impossible for this to happen other than, I don't know what, spyware or some junk?
