### ISSUE TITLE
blocked page still appear

### ISSUE THREAD

**Issue by chybbud** [TheRealJoelmatic/RemoveAdblockThing#370]
**Script version**
3.8

**Describe the bug**
block page still appear, and if i click allow youtube ads, something popup fundingchoices.google,com appears and it wont close even im go back to home page (im using NextDNS i dont think it affects on youtube)

i think i have same issue #369 

**Expected behavior**
it needs refresh page

**Screenshots**
![Screenshot (52)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/125054868/7bf4cebe-68ab-44c2-9741-2b5445949ea0)
![Screenshot (53)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/125054868/d6ea17ee-d5b0-4be6-a75f-78d8ed5b4510)

**Desktop (please complete the following information):**
 - OS:  Win 11 pro 23h2
 - Browser chrome
 - Version 121.0.6167.86
 
**Additional context**

**Comment by slzero-X** [comment]
How in the world are you guys getting this yet it's never happening to me? Implying its gonna happen to me as well? You have to have something in your browser or extensions that is triggering its anti-adblock.

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
