### ISSUE TITLE
YouTube Adblock Violation/Premium Purchase Pop Up happening with every video now upon opening; won't go away unless refresh screen

### ISSUE THREAD

**Issue by madstheaquarius** [TheRealJoelmatic/RemoveAdblockThing#393]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by MK147** [comment]
- Script version: 4.0
- Describe the bug: YouTube Adblock Violation/Premium Purchase Pop Up happening with every video now upon opening; won't go away unless refresh screen
- Expected behavior: Expecting to skip the pop up as it should be.
OS: [Windows]
Browser [chrome]
Version [124.0.6367.61 (Official Build) (64-bit)
![Screenshot (503)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/10328760/7a461ba9-3ecf-4e4a-9ce6-075a0685b092)
]
