### ISSUE TITLE
I can't autoplay or minamize videos in youtube

### ISSUE THREAD

**Issue by Kirbstomp19** [TheRealJoelmatic/RemoveAdblockThing#4032]
**Script version**
5.0 (latest)

**Describe the bug**
When I load up a video on youtube, I don't have access to audoplay or the ability to minimalize the video so I could look for other videos.

**Expected behavior**
Right before a video starts, the options for audoplaying and minimalizing videos removed completely. Its like they weren't there in the first place.

**Screenshots**
![youtube tapermonkey bug](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/173859203/5a5408aa-0f51-468e-86c9-f7458374344c)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Opera GX]
 - Version [10]

**Additional context**
Sorry if this is a bother lad. Its just been pestering me for a few days now and I just needed to let ya know.

**Comment by ToiYeuTien** [comment]
me too

**Comment by GroggyOtter** [comment]
It's because you're using v5.6, which is broken.  
This addon has been broken since v5.4.  

[Downgrade to v5.3](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/1765) until v5.7 comes out.  

I've been using 5.3 since 5.4 came out and it's still working perfectly.  

And if anyone says "5.3 isn't working!", scroll down further in that post and read the second comment I made about why it's probably not working.

**Comment by leafygreens7** [comment]
I am using 5.3 and yet every time the adblocker fast forwards an ad youtube recognizes it and the "Ad blockers violate youtube's terms of service" screen pops up. 

The same thing happens when I am playing a playlist, the Ad blockers violate youtube's terms of service" screen pops up and youtube automatically skips a lot of the videos in the playlist.

Is there a reason why 5.3 works for you but it does not work for me?

**Comment by GroggyOtter** [comment]
> I am using 5.3 and yet every time the adblocker fast forwards an ad youtube recognizes it and the "Ad blockers violate youtube's terms of service" screen pops up.
> 
> The same thing happens when I am playing a playlist, the Ad blockers violate youtube's terms of service" screen pops up and youtube automatically skips a lot of the videos in the playlist.
> 
> Is there a reason why 5.3 works for you but it does not work for me?

I'm using Windows 10 OS.  
Chrome browser.  
No YouTube addons other than TamperMonkey.  

I'd suggest uninstalling the script, reinstalling v5.3, and trying it again.  

In the past, I've had the script stop working temporarily (for whatever reason) and then it just kicks in.  
I've had this happen one time since 5.4 dropped and it went away after a couple videos. So it's definitely not a version thing or it would've kept happening.

Good luck with it, Leafy.
