### ISSUE TITLE
Playlists do not automatically play the next video when the current video finishes playing.

### ISSUE THREAD

**Issue by Pokest45-PZ** [TheRealJoelmatic/RemoveAdblockThing#4084]
When playing a playlist, once the video being played finishes, instead of switching to the next video in the playlist, the video displays its thumbnail and stops playing.

**Comment by GroggyOtter** [comment]
It's because you're using v5.6, which is broken.  
This addon has been broken since v5.4.  

[Downgrade to v5.3](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/1765) until v5.7 comes out.  
I've been using 5.3 since 5.4 came out and it's still working perfectly.  

And if anyone says "it's not working!", scroll down and read the second comment I made about why it's probably not working.
