### ISSUE TITLE
Age restriction

### ISSUE THREAD

**Issue by gcalado55** [TheRealJoelmatic/RemoveAdblockThing#4754]
**Script version**
latest

**Describe the bug**
When skipping the ad, if the video is age restriced the video can't be watched

**Screenshots**
![image](https://github.com/user-attachments/assets/0aaf8b06-463e-4019-b962-d778b5f521cd)

**Additional context**

**Comment by timgranata** [comment]
Without fully understanding the inner workings of the script, I think its because it takes the video and "tricks" your browser into thinking its being played externally (i.e. not on YouTube), Hence this error appears.  Presumably, it's a requirement for allowing the script to do its thing.  YouTube must have some sort of policy or restriction on age restricted videos being played externally.
