### ISSUE TITLE
black video player

### ISSUE THREAD

**Issue by therandomperson21** [TheRealJoelmatic/RemoveAdblockThing#94]
i downloaded it on edge and the video showed up black

**Comment by smuelre** [comment]
Every time I watch the video the screen goes black and the video doesn't start

**Comment by GiveNuts** [comment]
Same for me :(
![Screenshot 2023-10-27 040507](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/149128122/aa6a66c9-875d-446a-bc79-b2ce116abd5f)

**Comment by repsol-fireblade** [comment]
Same, but I kept open an Add-ons tab, and when I got the black screen I went to the tab & disabled uBlock, then back to YouTube - refreshed the page, and the video loaded (with no ads, despite uBlock being 'off', so the script seems to work), then back to Add-ons tab and re-enabled uBlock immediately.
Back to YouTube tab and the video is still loaded and plays fine. I can even scroll down into the comments now.

Previously I was blocking the elements of the warning message control using uBlock. That was working for a while but it was preventing me from scrolling down to the comments section in > 50% of videos. After updating Firefox it stopped working completely.

Firefox - Windows desktop.

Props to the devs behind this project.

Nothing will make me watch ads under ANY circumstances. I would stop using YouTube first.

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
